[workspace]
members = ["crates/cli", "crates/default-plugins/file-finder", "crates/default-plugins/vim-command-bar", "crates/manta-api", "crates/manta-core", "crates/manta-gui", "crates/manta_components"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
gpui = "0.2.2"
modalkit = "0.0.25"
nucleo = "0.5.0"
ropey = "1.6.1"
tree-sitter = "0.26.12"
walkdir = "2.5.0"
cc = "1.0"
manta_components = { path = "./crates/manta_components/"}
manta-core = {path = "./crates/manta-core/"}
manta-gui = { path = "./crates/manta-gui/" }
manta-api = { path = "./crates/manta-api/"}

file-finder = {path = "./crates/default-plugins/file-finder/"}
vim-command-bar = {path = "./crates/default-plugins/vim-command-bar/"}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

